### ISSUE TITLE
Uninitialized

### ISSUE THREAD

**Issue by alexgoodell** [alexgoodell/go-mdism#12]
Is cycle 0 the same as unin1 and unin2? Or how does that work exactly?

**Comment by Vreman** [comment]
Yes so you explained that unin1 and unin 2 both are part of cycle 0, which is the initialization phase.

But the disease prevalences only get simulated at cycle 1. So the prevalences at cycle 1 are actually the starting prevalences, from which the model starts simulating. So I should compare cycle 1 in GO with what I called 'year 0' in excel, and I am going to add another cycle to the GO model.

That is necessary because the starting prevalences are based on 2010. So cycle 1 represents 2010. To model until 2035, I need 25 extra cycles, so up until cycle 26.

**Comment by alexgoodell** [comment]
Right. Actually, since we have two initialization stages, we should start tracking from cycle 2. so, to get from 2010 to 2035, we'll need to input cycles 0 through 26, which will give us 2 through 27 as outputs, correct?

Better to have too many years output than too few

**Comment by Vreman** [comment]
Agreed. 0 to 26 gives us results for 2 to 27 (2011 to 2035), with 2010 as the pre-simulation year.
I will add the cycle now.
