### ISSUE TITLE
Age entry

### ISSUE THREAD

**Issue by alexgoodell** [alexgoodell/go-mdism#13]
Entry of new people (all people?) causes them to be 21 before they actualy start being simulated. Fix this.

**Comment by Vreman** [comment]
Because generating the new people sets them at the uninitialized state. When we generate them as being 20 years old, they only start to be part of the model when they are 21.

We either have to skip the uninitialized state (but I guess we need that to determine their RAS risk profile), or maybe introduce age 19 into the model? Or can we force them to stay 20 one extra year?

**Comment by alexgoodell** [comment]
I think it applies to all people, since they will still be in an uninitialized state #2 in NAFLD at age 20. I think we can do either 
- option 1: add an unintialized 2 state to the age model
- option 2: add age 19

**Comment by Vreman** [comment]
I have thought about this and I think I prefer option 1.
In my opinion, it would be preferred to keep the initiation phase and the model simulation seperated as best we can. With an unin2 it is clear that these people are not yet part of the model.
We would have to add those for ethnicity, sex and fructose as well right?

Can I just add them to the states CSV and review all input files for changed states?
I would also have to check the hardcodings for age & other stuff in the code.
Is there anything else I need to change to make this function properly?

**Comment by Vreman** [comment]
Tried adding the unin2 for age, sex, ethnicity and fructose. 
Had to change most other input files as well to make sure the states matched.
Also changed 2 times 22 (for age state) in the code to 26.

Kept getting the same error ("No TPs found with getTransitionProbByRAS for m r a s"); cannot figure out why.

People are still entering the model too early. This can be fixed by setting the 'if cycle id' > 1 instead of 0, for when new people should enter.

The problem that remains is that there is nobody entering in the last cycle

**Comment by alexgoodell** [comment]
did we solve this?

**Comment by alexgoodell** [comment]
Fixed
