### ISSUE TITLE
Set up PSA reporting

### ISSUE THREAD

**Issue by alexgoodell** [alexgoodell/go-mdism#8]
Set up PSA reporting - natural events, PSA switch etc - Alex to complete

**Comment by Vreman** [comment]
The best would be if there were two output documents: 

1 with events, prevalences (in all 7 models), costs, YLDs, YLLs and DALYs specified per cycle to be filled when we run a single simulation (so we can check how everything is functioning and calibrate). This can also be a combination of 2 or 3 files; we can use the state_populations to get all the prevalences, we just need files for the others. It is easy to write a macro (/python code) to combine the documents and order everything.

And a second output file that is generated when we run the model multiple times. We do not need the outputs per cycle in this file. We would need:
The prevalence at cycle 25 (of all states)
The total amount of events (per state, only for T2D, CHD and HCC)
The total amount of deaths (split per natural deaths, liver deaths, T2D deaths, CHD deaths)
Total amount of DALYs (split per relevant state)
Total costs (split per relevant state)

I do not know if Jim agrees, since it will be hard to produce a nice graph when we only have the year 25 prevalence and total amount of DALYs and costs.
But I presume it will be very hard to keep track of all these things per cycle and state (that would mean 26 cycles \* 10 states \* 4 categories = 1000 results per simulation). 4 categories being prevalence, events, DALYs, costs. We wouldn't need to keep track of RAS.

1000 per simulation would mean 10 to 30 million after iterations. This might still be ok.

What do you think? Would it be feasible to keep track of them per cycle when we iterate?
Is there a way to print this to one or a few CSV's? (but not 30,000)

I will also discuss this with Jim 07-07

**Comment by alexgoodell** [comment]
Talk about this with Jim tommorrow and update me, I can implement.
